[package]
name = "neat_experiments"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "1.1.0"
itertools = "0.11.0"
rand = "0.8.5"
tailcall = "0.1.6"
